/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTextRouteImport } from './routes/api/text'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiFileBoxNameRouteImport } from './routes/api/file/$box/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextRoute = ApiTextRouteImport.update({
  id: '/api/text',
  path: '/api/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileBoxNameRoute = ApiFileBoxNameRouteImport.update({
  id: '/api/file/$box/$name',
  path: '/api/file/$box/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRoute
  '/api/text': typeof ApiTextRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/file/$box/$name': typeof ApiFileBoxNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRoute
  '/api/text': typeof ApiTextRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/file/$box/$name': typeof ApiFileBoxNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/files': typeof ApiFilesRoute
  '/api/text': typeof ApiTextRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/file/$box/$name': typeof ApiFileBoxNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/files'
    | '/api/text'
    | '/api/upload'
    | '/api/file/$box/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/files' | '/api/text' | '/api/upload' | '/api/file/$box/$name'
  id:
    | '__root__'
    | '/'
    | '/api/files'
    | '/api/text'
    | '/api/upload'
    | '/api/file/$box/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiTextRoute: typeof ApiTextRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiFileBoxNameRoute: typeof ApiFileBoxNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/text': {
      id: '/api/text'
      path: '/api/text'
      fullPath: '/api/text'
      preLoaderRoute: typeof ApiTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/$box/$name': {
      id: '/api/file/$box/$name'
      path: '/api/file/$box/$name'
      fullPath: '/api/file/$box/$name'
      preLoaderRoute: typeof ApiFileBoxNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiTextRoute: ApiTextRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiFileBoxNameRoute: ApiFileBoxNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
